

FROM centos:7 

ENV JAVA_VERSION_MAJOR=8 \
    JAVA_VERSION_MINOR=144 \
    JAVA_VERSION_BUILD=01 \
    JAVA_URL_HASH=090f390dda5b47b9b721c7dfaa008135 \
    SPARK_HOME=/opt/spark/latest \
    Z_VERSION="0.8.2" \
    Z_HOME="/opt/zeppelin/latest" 
ENV LOG_TAG="[ZEPPELIN_$Z_VERSION]:" 
RUN echo $LOG_TAG
# Set environment variables.
ENV HOME /root
ENV JDK_HOME /usr/lib/jvm/java/
ENV JAVA_HOME /usr/lib/jvm/java
ENV JAVA_EXE /usr/lib/jvm/java/jre/bin/java
ENV JRE_HOME /usr/lib/jvm/java/jre
ENV LANG C.UTF-8
# Fixes ZEPPELIN-4371
ENV ZEPPELIN_ADDR 0.0.0.0

RUN set -ex
# Install packages
RUN echo "$LOG_TAG Installing Yum Packages" && \
    yum install -y wget && \
    yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel git && \
    #yum install -y xeyes && \
    yum install -y krb5-workstation && \
    yum install -y unzip && \
    #yum install -y update && \
    yum install -y bzip2 ca-certificates && \
    #libglib2.0-0 libxext6 libsm6 libxrender1 && \
    #git && \
    yum clean all

#Install Minicondayum instal grp
RUN echo "$LOG_TAG Install miniconda3 related packages" && \
    echo 'export PATH=/opt/miniconda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    /bin/bash miniconda.sh -b -p /opt/miniconda && \
    rm miniconda.sh
ENV PATH /opt/miniconda/bin:$PATH

RUN echo "$LOG_TAG Install python related packages" && \
    conda config --set always_yes yes --set changeps1 no && \
    conda update -q conda && \
    conda info -a && \
    conda config --add channels conda-forge && \
    conda install pandas matplotlib numpy scikit-learn pandasql ipython jupyter grpcio protobuf bokeh

# Install Spark
 RUN echo "$LOG_TAG Installing Spark" && \
    set -ex && \
    mkdir -p /opt/spark && \
    wget -q http://apache.mirror.anlx.net/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz && \
    tar -xf spark-2.4.5-bin-hadoop2.7.tgz -C /opt/spark && \
    rm spark-2.4.5-bin-hadoop2.7.tgz && \
    ln -s /opt/spark/spark-2.4.5-bin-hadoop2.7/ /opt/spark/latest && \
    wget -P /opt/spark/latest/jars/ https://repo1.maven.org/maven2/com/amazon/deequ/deequ/1.0.4/deequ-1.0.4.jar 

# Install Zeppelin
RUN echo "$LOG_TAG Installing Zeppelin" && \
    mkdir -p /opt/zeppelin/ && \
    wget -q http://apache.mirror.anlx.net/zeppelin/zeppelin-0.8.2/zeppelin-0.8.2-bin-all.tgz && \
    tar -xf zeppelin-0.8.2-bin-all.tgz -C /opt/zeppelin && \
    rm zeppelin-0.8.2-bin-all.tgz && \
    ln -s /opt/zeppelin/zeppelin-0.8.2-bin-all /opt/zeppelin/latest && \
    mkdir -p /data

EXPOSE 8080

#ENTRYPOINT [ "/usr/bin/tini", "--" ]
WORKDIR $Z_HOME
CMD ["bin/zeppelin.sh"]
